# -*- coding: utf-8 -*-
"""여기어때 크롤링 DB 적재

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fql6bgSWqq1P_qPOgBn9aF9-VJX9ezwd
"""

# 해외 링크 목록

city_data = {
                            "componentId": 1512,
                            "componentSeq": 2,
                            "componentType": 13,
                            "componentName": "해외 여행지 링크 (최대 60개)",
                            "contentGroups": [
                                {
                                    "contentGroupId": 3264,
                                    "contentGroupSeq": 1,
                                    "contentGroupType": 3,
                                    "appViewType": 10,
                                    "contents": [
                                        {
                                            "contentId": 62583,
                                            "contentSeq": 1,
                                            "contentValue": "오사카",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/오사카",
                                            "item": "62583",
                                            "pgMetaSType": "1512.62583",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62581,
                                            "contentSeq": 2,
                                            "contentValue": "후쿠오카",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/후쿠오카%20%2F%20훗쿠오카",
                                            "item": "62581",
                                            "pgMetaSType": "1512.62581",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62585,
                                            "contentSeq": 3,
                                            "contentValue": "도쿄 / 동경",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/도쿄%20%2F%20동경",
                                            "item": "62585",
                                            "pgMetaSType": "1512.62585",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62586,
                                            "contentSeq": 4,
                                            "contentValue": "다낭",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/베트남/다낭",
                                            "item": "62586",
                                            "pgMetaSType": "1512.62586",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62582,
                                            "contentSeq": 5,
                                            "contentValue": "싱가포르",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/싱가포르/싱가포르%20%2F%20싱가폴",
                                            "item": "62582",
                                            "pgMetaSType": "1512.62582",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62584,
                                            "contentSeq": 6,
                                            "contentValue": "방콕",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/태국/방콕%20%2F%20크룽텝",
                                            "item": "62584",
                                            "pgMetaSType": "1512.62584",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62592,
                                            "contentSeq": 7,
                                            "contentValue": "괌",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/괌/괌",
                                            "item": "62592",
                                            "pgMetaSType": "1512.62592",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62587,
                                            "contentSeq": 8,
                                            "contentValue": "세부",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/필리핀/세부",
                                            "item": "62587",
                                            "pgMetaSType": "1512.62587",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62590,
                                            "contentSeq": 9,
                                            "contentValue": "나트랑 / 나짱",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/베트남/나트랑%20%2F%20나짱%20%2F%20냐짱",
                                            "item": "62590",
                                            "pgMetaSType": "1512.62590",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62588,
                                            "contentSeq": 10,
                                            "contentValue": "교토",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/교토%20%2F%20쿄토",
                                            "item": "62588",
                                            "pgMetaSType": "1512.62588",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62591,
                                            "contentSeq": 11,
                                            "contentValue": "타이베이",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/대만/타이베이",
                                            "item": "62591",
                                            "pgMetaSType": "1512.62591",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62589,
                                            "contentSeq": 12,
                                            "contentValue": "보라카이",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/필리핀/보라카이",
                                            "item": "62589",
                                            "pgMetaSType": "1512.62589",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62593,
                                            "contentSeq": 13,
                                            "contentValue": "삿포로",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/삿포로",
                                            "item": "62593",
                                            "pgMetaSType": "1512.62593",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62594,
                                            "contentSeq": 14,
                                            "contentValue": "유후",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/유후%20%2F%20유후인",
                                            "item": "62594",
                                            "pgMetaSType": "1512.62594",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62595,
                                            "contentSeq": 15,
                                            "contentValue": "홍콩",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/홍콩/홍콩",
                                            "item": "62595",
                                            "pgMetaSType": "1512.62595",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62596,
                                            "contentSeq": 16,
                                            "contentValue": "호놀룰루 (HI)",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/미국/호놀룰루%20%28HI%29%20%2F%20호눌룰루",
                                            "item": "62596",
                                            "pgMetaSType": "1512.62596",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62598,
                                            "contentSeq": 17,
                                            "contentValue": "오키나와 본섬",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/오키나와%20본섬",
                                            "item": "62598",
                                            "pgMetaSType": "1512.62598",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62597,
                                            "contentSeq": 18,
                                            "contentValue": "호치민",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/베트남/호치민%20%2F%20사이공",
                                            "item": "62597",
                                            "pgMetaSType": "1512.62597",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62599,
                                            "contentSeq": 19,
                                            "contentValue": "보홀",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/필리핀/보홀",
                                            "item": "62599",
                                            "pgMetaSType": "1512.62599",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62600,
                                            "contentSeq": 20,
                                            "contentValue": "코타키나발루",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/말레이시아/코타키나발루",
                                            "item": "62600",
                                            "pgMetaSType": "1512.62600",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62605,
                                            "contentSeq": 21,
                                            "contentValue": "호이안",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/베트남/호이안",
                                            "item": "62605",
                                            "pgMetaSType": "1512.62605",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62601,
                                            "contentSeq": 22,
                                            "contentValue": "파타야",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/태국/파타야",
                                            "item": "62601",
                                            "pgMetaSType": "1512.62601",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62602,
                                            "contentSeq": 23,
                                            "contentValue": "마카오",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/마카오/마카오",
                                            "item": "62602",
                                            "pgMetaSType": "1512.62602",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62603,
                                            "contentSeq": 24,
                                            "contentValue": "발리",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/인도네시아/발리",
                                            "item": "62603",
                                            "pgMetaSType": "1512.62603",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62604,
                                            "contentSeq": 25,
                                            "contentValue": "푸쿽 / 푸꾸옥 섬",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/베트남/푸쿽%20%2F%20푸꾸옥%20섬%20%2F%20푸꾸옥",
                                            "item": "62604",
                                            "pgMetaSType": "1512.62604",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62606,
                                            "contentSeq": 26,
                                            "contentValue": "파리",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/프랑스/파리",
                                            "item": "62606",
                                            "pgMetaSType": "1512.62606",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62611,
                                            "contentSeq": 27,
                                            "contentValue": "하노이",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/베트남/하노이",
                                            "item": "62611",
                                            "pgMetaSType": "1512.62611",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62608,
                                            "contentSeq": 28,
                                            "contentValue": "사이판",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/북마리아나%20제도/사이판",
                                            "item": "62608",
                                            "pgMetaSType": "1512.62608",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62612,
                                            "contentSeq": 29,
                                            "contentValue": "푸켓",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/태국/푸켓%20%2F%20푸껫",
                                            "item": "62612",
                                            "pgMetaSType": "1512.62612",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62609,
                                            "contentSeq": 30,
                                            "contentValue": "시드니",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/호주/시드니",
                                            "item": "62609",
                                            "pgMetaSType": "1512.62609",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62607,
                                            "contentSeq": 31,
                                            "contentValue": "마닐라",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/필리핀/마닐라",
                                            "item": "62607",
                                            "pgMetaSType": "1512.62607",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62610,
                                            "contentSeq": 32,
                                            "contentValue": "벳푸",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/벳푸",
                                            "item": "62610",
                                            "pgMetaSType": "1512.62610",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62613,
                                            "contentSeq": 33,
                                            "contentValue": "뉴욕 (NY)",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/미국/뉴욕%20%28NY%29",
                                            "item": "62613",
                                            "pgMetaSType": "1512.62613",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62614,
                                            "contentSeq": 34,
                                            "contentValue": "로마",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/이탈리아/로마",
                                            "item": "62614",
                                            "pgMetaSType": "1512.62614",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62615,
                                            "contentSeq": 35,
                                            "contentValue": "나고야",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/나고야",
                                            "item": "62615",
                                            "pgMetaSType": "1512.62615",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62616,
                                            "contentSeq": 36,
                                            "contentValue": "치앙마이",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/태국/치앙마이",
                                            "item": "62616",
                                            "pgMetaSType": "1512.62616",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62617,
                                            "contentSeq": 37,
                                            "contentValue": "앙헬레스 / 클락",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/필리핀/앙헬레스%20%2F%20클락",
                                            "item": "62617",
                                            "pgMetaSType": "1512.62617",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62618,
                                            "contentSeq": 38,
                                            "contentValue": "런던",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/영국/런던",
                                            "item": "62618",
                                            "pgMetaSType": "1512.62618",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62619,
                                            "contentSeq": 39,
                                            "contentValue": "판티엣",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/베트남/판티엣%20%2F%20판티앳",
                                            "item": "62619",
                                            "pgMetaSType": "1512.62619",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62620,
                                            "contentSeq": 40,
                                            "contentValue": "바르셀로나",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/스페인/바르셀로나",
                                            "item": "62620",
                                            "pgMetaSType": "1512.62620",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62623,
                                            "contentSeq": 41,
                                            "contentValue": "라스베이거스 / 라스베가스 (NV)",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/미국/라스베이거스%20%2F%20라스베가스%20%28NV%29",
                                            "item": "62623",
                                            "pgMetaSType": "1512.62623",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62624,
                                            "contentSeq": 42,
                                            "contentValue": "고베",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/고베",
                                            "item": "62624",
                                            "pgMetaSType": "1512.62624",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62626,
                                            "contentSeq": 43,
                                            "contentValue": "하코네",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/하코네%20%2F%20하꼬네",
                                            "item": "62626",
                                            "pgMetaSType": "1512.62626",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62625,
                                            "contentSeq": 44,
                                            "contentValue": "노보리베츠",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/노보리베츠%20%2F%20노보리베쓰",
                                            "item": "62625",
                                            "pgMetaSType": "1512.62625",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62621,
                                            "contentSeq": 45,
                                            "contentValue": "쿠알라룸푸르",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/말레이시아/쿠알라룸푸르",
                                            "item": "62621",
                                            "pgMetaSType": "1512.62621",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62622,
                                            "contentSeq": 46,
                                            "contentValue": "로스앤젤레스 (CA)",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/미국/로스앤젤레스%20%28CA%29%20%2F%20엘에이%20%28LA%29",
                                            "item": "62622",
                                            "pgMetaSType": "1512.62622",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62628,
                                            "contentSeq": 47,
                                            "contentValue": "그린델발트",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/스위스/그린델발트",
                                            "item": "62628",
                                            "pgMetaSType": "1512.62628",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62627,
                                            "contentSeq": 48,
                                            "contentValue": "프라하",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/체코/프라하",
                                            "item": "62627",
                                            "pgMetaSType": "1512.62627",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62629,
                                            "contentSeq": 49,
                                            "contentValue": "요코하마",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/요코하마",
                                            "item": "62629",
                                            "pgMetaSType": "1512.62629",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62632,
                                            "contentSeq": 50,
                                            "contentValue": "인터라켄",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/스위스/인터라켄",
                                            "item": "62632",
                                            "pgMetaSType": "1512.62632",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62631,
                                            "contentSeq": 51,
                                            "contentValue": "달랏",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/베트남/달랏",
                                            "item": "62631",
                                            "pgMetaSType": "1512.62631",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62630,
                                            "contentSeq": 52,
                                            "contentValue": "꼬사무이 / 코사무이",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/태국/꼬사무이%20%2F%20코사무이%20%2F%20사무이섬",
                                            "item": "62630",
                                            "pgMetaSType": "1512.62630",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62633,
                                            "contentSeq": 53,
                                            "contentValue": "끄라비 / 크라비",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/태국/끄라비%20%2F%20크라비",
                                            "item": "62633",
                                            "pgMetaSType": "1512.62633",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62634,
                                            "contentSeq": 54,
                                            "contentValue": "비엔나 / 빈",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/오스트리아/비엔나%20%2F%20빈",
                                            "item": "62634",
                                            "pgMetaSType": "1512.62634",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62635,
                                            "contentSeq": 55,
                                            "contentValue": "오타루",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/오타루",
                                            "item": "62635",
                                            "pgMetaSType": "1512.62635",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62638,
                                            "contentSeq": 56,
                                            "contentValue": "기타큐슈",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/기타큐슈",
                                            "item": "62638",
                                            "pgMetaSType": "1512.62638",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62636,
                                            "contentSeq": 57,
                                            "contentValue": "나리타",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/일본/나리타",
                                            "item": "62636",
                                            "pgMetaSType": "1512.62636",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62637,
                                            "contentSeq": 58,
                                            "contentValue": "부다페스트",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/헝가리/부다페스트",
                                            "item": "62637",
                                            "pgMetaSType": "1512.62637",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62639,
                                            "contentSeq": 59,
                                            "contentValue": "멜버른 / 멜번",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/호주/멜버른%20%2F%20멜번",
                                            "item": "62639",
                                            "pgMetaSType": "1512.62639",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        },
                                        {
                                            "contentId": 62640,
                                            "contentSeq": 60,
                                            "contentValue": "피렌체 / 플로렌스",
                                            "landingType": 2,
                                            "landingInfo": "http://www.yeogi.com/city/이탈리아/피렌체%20%2F%20플로렌스",
                                            "item": "62640",
                                            "pgMetaSType": "1512.62640",
                                            "exhibitStartDateTime": "2023-11-03T00:00:00",
                                            "exhibitEndDateTime": "2033-11-03T23:59:59",
                                            "contentType": 1
                                        }
                                    ]
                                }
                            ]
                        }

# 모듈 임포트

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time
import json
import requests
from bs4 import BeautifulSoup
import re
from selenium.common.exceptions import TimeoutException
from selenium.webdriver import ActionChains
from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
import psycopg2
from psycopg2 import sql
from datetime import datetime

# chrome 옵션 설정

chrome_options = Options()
# chrome_options.add_argument("--headless")  # Headless 모드 설정 (브라우저 UI 없이 실행)
chrome_options.add_argument("--no-sandbox")  # 샌드박스 모드 비활성화
# chrome_options.add_argument("--disable-dev-shm-usage")  # /dev/shm 사용 비활성화
chrome_options.add_argument("--disable-gpu")  # GPU 비활성화
chrome_options.add_argument("--window-size=1920x1080")  # 윈도우 크기 설정
chrome_options.add_argument('--disable-extensions')  # 브라우저 확장 기능 비활성화
chrome_options.add_argument("--disable-cache")
chrome_options.add_argument("--proxy-server='direct://'")
chrome_options.add_argument("--proxy-bypass-list=*")
chrome_options.add_argument("--incognito")  # 시크릿 모드로 브라우저 실행

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)

# 총 검색 호텔 개수 및 총 검색 페이지 수 계산
def get_total_page_num(url):
  url_page = url + str(1)
  driver.get(url_page)
  html = driver.page_source
  soup = BeautifulSoup(html, "html.parser")

  try:
      WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, "header.css-1psit91 h1")))
      h1_tag = driver.find_element(By.CSS_SELECTOR, "header.css-1psit91 h1")
      total_result_text = h1_tag.text.strip()
      total_result_num = "".join(char for char in total_result_text if char.isdigit())
      print("총 검색 호텔 개수:", total_result_num)
      return int(total_result_num) // 20 + 1

  except Exception as e:
      print(f"Error in get_total_page_num: {e}")
      return 0

# 날짜 차이 계산
def calculate_nights(start_date, end_date):

    checkin_date = datetime.strptime(start_date, '%Y-%m-%d')
    checkout_date = datetime.strptime(end_date, '%Y-%m-%d')

    duration = checkout_date - checkin_date

    return duration.days

# 크롤링 함수
def Crawling_domestic(url, total_page_num,  conn, cur):
    hotel_data = []
    link_list = []
    price_dict = {}

    for page_num in range(1, total_page_num+1):
        url_Crawling = url + str(page_num)
        driver.get(url_Crawling)
        print(f"Fetching page {page_num} with URL: {url_Crawling}")
        time.sleep(5)
        html = driver.page_source
        soup = BeautifulSoup(html, "html.parser")

        # 모든 상품 가져오기
        items = soup.select(".gc-thumbnail-type-seller-card")
        print(f"Found {len(items)} items on page {page_num}")

        # 유효한 상품 리스트 초기화
        valid_items = []

        # 가격 가져오기 및 필터링
        for item in items:

            # item 내에 가격이 있는지 확인
            price = item.select_one(".css-5r5920")
            price = "" if not price else price.text.strip()

            if price:
                # 가격이 있을 경우에만 유효한 상품 리스트에 추가
                price = int(price.replace(',', ''))
                valid_items.append(item)

                # 상품 접속 링크 가져오기
                link = f"https://www.yeogi.com{item.get('href')}"
                link_list.append(link)

                # 가격과 링크 딕셔너리에 저장
                price_dict[link] = price

    # 상세 페이지 접속
    for link in link_list:
        driver.get(link)
        time.sleep(5)
        html = driver.page_source
        soup = BeautifulSoup(html, "html.parser")

        try:
            # 호텔 이름 추출
            name = driver.find_element(By.CSS_SELECTOR, 'h1.css-e3nxqe')
            name = "" if not name else name.text.strip()

            # 평점 추출
            rating = driver.find_element(By.CSS_SELECTOR, 'div.css-1hf9b3s')
            rating = "" if not rating else rating.text.strip()

            # 리뷰 수 추출
            review = driver.find_element(By.CSS_SELECTOR, 'span.css-1m0qn1y')
            review = "" if not review else review.text.strip()
            match = re.search(r'(\d{1,3}(?:,\d{3})*)개 리뷰', review)
            review_count = match.group(1)
            review_count = int(review_count.replace(',', ''))

            # 방 가격
            room_price = price_dict[link]

            # 부가 옵션
            option_list = []
            room_options = soup.select(".css-i0atbk")

            for room_option in room_options:
              option = room_option.select_one('p.css-i3rab1')
              option = "" if not option else option.text.strip()
              option_list.append(option)
              option_ = ', '.join(option_list)

            # 국내/해외
            is_domestic = True

            # 머무는 기간
            period = calculate_nights(start_date, end_date)

            # 1박 당 가격
            price_per_day = int(room_price)/int(period)

            # 조식
            is_breakfast = False

            insert_time = datetime.now()

            # PostgreSQL에 데이터 삽입
            insert_query = sql.SQL("""
                INSERT INTO Accommodation_info (accommodation_name, rate, review, nearest_city, is_domestic, check_in,
                check_out, check_period, num_adult, num_child, price_total, price_per_day, is_breakfast, option, fetched_date)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """)

            try:
                cur.execute(insert_query, (name, rating, review_count, region, is_domestic, start_date, end_date, period,
                                          adult, child, room_price, price_per_day, is_breakfast, option_, insert_time))
                conn.commit()  # Commit after each insert
                print(f"Data inserted and committed for: {name}")
            except Exception as e:
                print(f"SQL 실행 중 오류 발생: {e}")

        except Exception as e:
            print(f"호텔 정보 추출 중 오류 발생: {e}")

    print("All data committed to the database.")
    return 0

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
link_list = []
price_list = []
hotel_data = []

# 나라별 URL 가져오는 함수
def city_id(region):
    search_terms = region.split()
    for group in city_data['contentGroups']:
        for item in group['contents']:
            if all(term in item['contentValue'] or term in item['landingInfo'] for term in search_terms):
                return item['landingInfo']
    return None

def calculate_nights(start_date, end_date):

    # 날짜 문자열을 datetime 객체로 변환
    checkin_date = datetime.strptime(start_date, '%Y-%m-%d')
    checkout_date = datetime.strptime(end_date, '%Y-%m-%d')

    # 날짜 차이 계산
    duration = checkout_date - checkin_date

    # 결과 반환
    return duration.days


# 객실 및 인원 수 선택하는 함수
def set(rooms, adults, children):
    try:
        # 페이지가 완전히 로드될 때까지 대기
        WebDriverWait(driver, 20).until(
            lambda driver: driver.execute_script('return document.readyState') == 'complete'
        )
        print("객실 및 인원 수를 선택하는 창이 완전히 로드되었습니다.")

        # 모든 gc-stepper 요소를 가져옴
        stepper_elements = WebDriverWait(driver, 10).until(
            EC.presence_of_all_elements_located((By.CSS_SELECTOR, '.gc-stepper'))
        )

        # 객실 수 조절을 위한 첫 번째 gc-stepper 요소 선택
        room_stepper = stepper_elements[0]
        room_minus_button = room_stepper.find_element(By.CSS_SELECTOR, '.gc-icon-round-button.css-11zi1w5')
        room_plus_button = room_stepper.find_elements(By.CSS_SELECTOR, '.gc-icon-round-button.css-11zi1w5')[1]
        room_display = room_stepper.find_element(By.CSS_SELECTOR, '.css-gcrqic')

        # 스크롤을 통해 버튼이 화면에 나타나도록 함
        driver.execute_script("arguments[0].scrollIntoView(true);", room_minus_button)
        driver.execute_script("arguments[0].scrollIntoView(true);", room_plus_button)

        # 현재 객실 수 가져오기
        current_rooms = int(room_display.text)

        # 객실 수 설정
        while current_rooms > rooms:
            WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable(room_minus_button)
            ).click()
            current_rooms = int(room_display.text)

        while current_rooms < rooms:
            WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable(room_plus_button)
            ).click()
            current_rooms = int(room_display.text)

        print(f"객실 수를 {current_rooms}로 선택하였습니다.")

        # 성인 수 조절을 위한 두 번째 gc-stepper 요소 선택
        adult_stepper = stepper_elements[1]
        adult_minus_button = adult_stepper.find_element(By.CSS_SELECTOR, '.gc-icon-round-button.css-11zi1w5')
        adult_plus_button = adult_stepper.find_elements(By.CSS_SELECTOR, '.gc-icon-round-button.css-11zi1w5')[1]
        adult_display = adult_stepper.find_element(By.CSS_SELECTOR, '.css-gcrqic')

        driver.execute_script("arguments[0].scrollIntoView(true);", adult_minus_button)
        driver.execute_script("arguments[0].scrollIntoView(true);", adult_plus_button)

        current_adults = int(adult_display.text)

        # 성인 수 설정
        while current_adults > adults:
            WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable(adult_minus_button)
            ).click()
            current_adults = int(adult_display.text)

        while current_adults < adults:
            WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable(adult_plus_button)
            ).click()
            current_adults = int(adult_display.text)

        print(f"성인 수를 {current_adults}로 선택하였습니다.")

        # 아동 수 조절을 위한 세 번째 gc-stepper 요소 선택
        child_stepper = stepper_elements[2]
        child_minus_button = child_stepper.find_element(By.CSS_SELECTOR, '.gc-icon-round-button.css-11zi1w5')
        child_plus_button = child_stepper.find_elements(By.CSS_SELECTOR, '.gc-icon-round-button.css-11zi1w5')[1]
        child_display = child_stepper.find_element(By.CSS_SELECTOR, '.css-gcrqic')

        driver.execute_script("arguments[0].scrollIntoView(true);", child_minus_button)
        driver.execute_script("arguments[0].scrollIntoView(true);", child_plus_button)

        current_children = int(child_display.text)

        # 아동 수 설정
        while current_children > children:
            WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable(child_minus_button)
            ).click()
            current_children = int(child_display.text)

        while current_children < children:
            WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable(child_plus_button)
            ).click()
            current_children = int(child_display.text)

        print(f"아동 수를 {current_children}로 선택하였습니다.")

        print("객실 및 인원 수 선택이 완료되었습니다.")

    except Exception as e:
        print(f"오류 발생: {e}")
        screenshot_path = '/content/error_screenshot.png'
        driver.save_screenshot(screenshot_path)  # 스크린샷 저장
        with open('/content/page_source.html', 'w', encoding='utf-8') as f:
            f.write(driver.page_source)  # 페이지 소스 저장
        print(f"객실 및 인원 수 선택 오류 발생 시 스크린샷이 저장되었습니다: {screenshot_path}")


# URL을 파싱하여 쿼리 파라미터를 수정하는 함수
def update_query_params(url, params):
    parsed_url = urlparse(url)
    query_params = parse_qs(parsed_url.query)

    # params는 {'param1': 'value1', 'param2': 'value2'} 형태
    query_params.update(params)

    new_query_string = urlencode(query_params, doseq=True)
    new_url = urlunparse(parsed_url._replace(query=new_query_string))
    return new_url


# 현재 페이지의 상품 접속 링크들을 가져오는 함수
def get_page_info(driver, link_list):
    # 현재 페이지의 HTML을 가져오기
    html = driver.page_source
    soup = BeautifulSoup(html, 'html.parser')

    # 상품 접속 링크 가져오기
    items = soup.select(".gc-thumbnail-type-seller-card.css-wels0m")
    for item in items:
        link = f"https://www.yeogi.com{item.get('href')}"
        link_list.append(link)

        price = item.select_one(".css-5r5920")
        price = "" if not price else price.text.strip()
        price = int(price.replace(',', ''))
        price_list.append(price)
    print(f"{len(link_list)}개의 링크를 모으는 중입니다.")

# 다음 페이지로 넘어가는 함수
def go_to_next_page(driver):
    try:
        # 스크롤을 아래로 이동하여 다음 페이지 버튼이 보이도록 함
        next_button = WebDriverWait(driver, 30).until(
            EC.presence_of_element_located((By.XPATH, '//*[@id="__next"]/div[1]/main/section/div[2]/div[2]/div/div/button[2]'))
        )

        # 버튼이 비활성화되어 있으면 마지막 페이지로 간주
        if not next_button.is_enabled() or 'disabled' in next_button.get_attribute('class'):
            print("마지막 페이지입니다.")
            return False

        # 버튼이 화면에 완전히 나타나도록 스크롤
        driver.execute_script("arguments[0].scrollIntoView(true);", next_button)
        time.sleep(1)  # 스크롤 후 약간 대기

        # JavaScript로 버튼 클릭
        driver.execute_script("arguments[0].click();", next_button)
        time.sleep(2)  # 페이지가 로드되는 시간을 고려하여 잠시 대기
        return True

    except Exception as e:
        print(f"다음 페이지로 이동 중 오류 발생: {e}")
        return False


# 크롤링 함수
def Crawling_international(url, start_date, end_date, room, adult, child,  conn, cur):
    hotel_data = []
    driver.get(url)

    try:
        # 1. 페이지가 완전히 로드될 때까지 대기
        WebDriverWait(driver, 20).until(
            lambda driver: driver.execute_script('return document.readyState') == 'complete'
        )
        print("해당 나라의 예약 페이지가 완전히 로드되었습니다.")

        # '객실1, 성인2' 버튼 대기 및 클릭
        action = ActionChains(driver)

        button = WebDriverWait(driver, 20).until(
            EC.element_to_be_clickable((By.XPATH, '//*[@id="__next"]/div[1]/main/section[1]/div[2]/div/div[2]/form/div[3]/div[1]/div/div'))
        )
        driver.execute_script("arguments[0].scrollIntoView();", button)
        WebDriverWait(driver, 10).until(EC.visibility_of(button))

        action.click(button).perform()
        print("'객실1, 성인2' 버튼이 클릭되었습니다.")

        # 2. 객실 및 인원 수 선택
        set(room, adult, child)

        # 3. 검색 버튼 클릭
        button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//*[@id="__next"]/div[1]/main/section[1]/div[2]/div/div[2]/form/div[4]/button'))
        )

        action = ActionChains(driver)
        action.click(button).perform()
        time.sleep(5)
        print("'검색' 버튼이 클릭되고 새 탭으로 전환되었습니다.")

        # 4. 원하는 날짜로 변경
        current_url = driver.current_url
        updated_url = update_query_params(current_url, {'checkIn': start_date, 'checkOut': end_date})

        # 5. 새 url로 이동
        driver.get(updated_url)
        time.sleep(5)
        print("원하는 조건의 호텔 목록이 주어진 페이지로 이동되었습니다.")

        # 6. 페이지 이동
        page_counter = 0  # 페이지 카운터 초기화

        while True:
            get_page_info(driver, link_list)  # 현재 페이지 정보 수집

            # 다음 페이지로 이동 시도
            if not go_to_next_page(driver):
                print(f"더 이상 페이지가 없습니다. 총 {page_counter + 1} 페이지 탐색 완료.")
                break  # 다음 페이지가 없을 경우 루프 종료

            page_counter += 1  # 페이지 카운터 증가

        # 7. 모은 링크 리스트에서 호텔 정보 수집하기
        # 상세 페이지 접속
        for link in link_list:
            driver.get(link)
            time.sleep(5)
            html = driver.page_source
            soup = BeautifulSoup(html, "html.parser")

            try:
                # 호텔 이름 추출
                name = driver.find_element(By.CSS_SELECTOR, 'h1.css-e3nxqe')
                name = "" if not name else name.text.strip()

                # 평점 추출
                rating = driver.find_element(By.CSS_SELECTOR, 'div.css-1hf9b3s')
                rating = "" if not rating else rating.text.strip()

                # 리뷰 수 추출
                review = driver.find_element(By.CSS_SELECTOR, 'span.css-1m0qn1y')
                review = "" if not review else review.text.strip()
                match = re.search(r'(\d{1,3}(?:,\d{3})*)개 리뷰', review)
                review_count = match.group(1)
                review_count = int(review_count.replace(',', ''))

                # 방 가격
                room_price = price_list[link_list.index(link)]

                # 부가 옵션
                option_list = []
                room_options = soup.select(".css-i0atbk")

                for room_option in room_options:
                  option = room_option.select_one('p.css-i3rab1')
                  option = "" if not option else option.text.strip()
                  option_list.append(option)
                  option_ = ', '.join(option_list)

                # 국내/해외
                is_domestic = False

                # 머무는 기간
                period = calculate_nights(start_date, end_date)

                # 1박 당 가격
                price_per_day = int(room_price)/int(period)

                # 조식
                is_breakfast = False

                insert_time = datetime.now()

                # PostgreSQL에 데이터 삽입
                insert_query = sql.SQL("""
                    INSERT INTO Accommodation_info (accommodation_name, rate, review, nearest_city, is_domestic, check_in,
                    check_out, check_period, num_adult, num_child, price_total, price_per_day, is_breakfast, option, fetched_date)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """)

                try:
                    cur.execute(insert_query, (name, rating, review_count, region, is_domestic, start_date, end_date, period,
                                              adult, child, room_price, price_per_day, is_breakfast, option_, insert_time))
                    conn.commit()  # Commit after each insert
                    print(f"Data inserted and committed for: {name}")
                except Exception as e:
                    print(f"SQL 실행 중 오류 발생: {e}")

            except Exception as e:
                print(f"호텔 정보 추출 중 오류 발생: {e}")

    except Exception as e:
        print(f"오류 발생: {e}")
        driver.save_screenshot('error_screenshot.png')  # 스크린샷 저장
        with open('page_source.html', 'w', encoding='utf-8') as f:
            f.write(driver.page_source)  # 페이지 소스 저장

    print("All data committed to the database.")
    return 0

# main 함수

if __name__ == "__main__":
    ans = input("국내/해외 중 하나를 입력하세요: ")

    if ans == "국내":
        region = input("지역명: ")
        start_date = input("체크인 날짜(0000-00-00): ")
        end_date = input("체크아웃 날짜(0000-00-00): ")
        adult = int(input("성인 수: "))
        child = int(input("아동 수: "))
        person = adult + child
        url = f"https://www.yeogi.com/domestic-accommodations?searchType=KEYWORD&keyword={region}&autoKeyword=&checkIn={start_date}&checkOut={end_date}&personal={person}&freeForm=false&page="
        total_page_num = get_total_page_num(url)
        print(f"총 검색 페이지 개수: {total_page_num}")

        # PostgreSQL 연결
        conn = psycopg2.connect(
            dbname="example_db",
            user="suji",
            password="1129",
            host="localhost",
            port="5432"
        )
        # DB와 상호작용하는 커서 (INSERT, DELETE 등)
        cur = conn.cursor()

        # 크롤러 작동
        if total_page_num > 0:
          Crawling_domestic(url, total_page_num, conn, cur)

        # 크롤러 종료 후 DB 연결 종료
        cur.close()
        conn.close()
        print("Database connection closed.")

    elif ans == "해외":
        region = input("해외 지역명: ")
        url = city_id(region)
        print(url)
        start_date = input("체크인 날짜(0000-00-00): ")
        end_date = input("체크아웃 날짜(0000-00-00): ")
        room = int(input("방 개수: "))
        adult = int(input("성인 수: "))
        child = int(input("아동 수: "))

        # PostgreSQL 연결
        conn = psycopg2.connect(
            dbname="example_db",
            user="suji",
            password="1129",
            host="localhost",
            port="5432"
        )
        # DB와 상호작용하는 커서 (INSERT, DELETE 등)
        cur = conn.cursor()

        # 크롤러 작동
        Crawling_international(url, start_date, end_date, room, adult, child, conn, cur)

        # 크롤러 종료 후 DB 연결 종료
        cur.close()
        conn.close()
        print("Database connection closed.")

    else:
        print("잘못된 입력입니다.")